---
# defaults file for fcos

fcos_stream: stable
fcos_arch: x86_64
fcos_platform: qemu
fcos_format: "qcow2.xz"
fcos_storage_location: "{{ playbook_dir }}/images"
fcos_extraction_location: "$HOME/.local/share/libvirt/images"
fcos_build_url: "https://builds.coreos.fedoraproject.org/streams/{{ fcos_stream }}.json"
fcos_gpg_key_location: "https://getfedora.org/static/fedora.gpg"
fcos_aws_region: us-east-2
